export async function mockAnalysis(uploadedText, baselineText) {
  await new Promise(r => setTimeout(r, 1800));
  return [
    {
      ruleId: 'GOVERNING_LAW',
      clause: '§ 12.2',
      original: 'Governed by the laws of Portugal. Exclusive jurisdiction of the Courts of Lisbon.',
      modified: 'Governed by the laws of England and Wales. Disputes submitted to the courts of London.',
      detail: 'Governing law changed from Portugal to England and Wales. Jurisdiction moved from Lisbon to London courts. This increases litigation cost and complexity for Appning by Forvia.',
      page: 3,
    },
    {
      ruleId: 'CONF_TERM',
      clause: '§ 9.2',
      original: 'Rights and obligations survive termination for 5 (five) years. Trade secrets survive indefinitely per Applicable Law.',
      modified: 'Rights and obligations survive termination for 2 (two) years. No trade secret carve-out.',
      detail: 'Survival period reduced from 5 years to 2 years. The trade secret carve-out has been removed.',
      page: 2,
    },
    {
      ruleId: 'CONF_SCOPE',
      clause: '§ 2',
      original: 'Confidential Information includes oral, written, electronic forms. Includes derived information and the fact that discussions are taking place.',
      modified: 'Confidential Information limited to written or electronic communications expressly marked as confidential.',
      detail: 'Definition narrowed to require confidentiality marking. Oral disclosures are no longer protected.',
      page: 1,
    },
    {
      ruleId: 'AGREEMENT_TERM',
      clause: '§ 9.1',
      original: 'Agreement terminates on the earlier of: execution of definitive agreement, written notice, or 1 year from signing.',
      modified: 'Agreement terminates on the earlier of: execution of definitive agreement, written notice with 60 days prior notice, or 6 months from signing.',
      detail: 'Base term reduced from 1 year to 6 months. Termination by written notice now requires 60 days prior notice.',
      page: 2,
    },
    {
      ruleId: 'TERMINATION_NOTICE',
      clause: '§ 9.1.ii',
      original: 'Either party may terminate by written notice at any time with no minimum notice period.',
      modified: 'Either party may terminate by providing 60 (sixty) days prior written notice.',
      detail: 'A 60-day minimum notice period introduced. This locks parties in and delays exit from a failed evaluation.',
      page: 2,
    },
    {
      ruleId: 'INDEMNIFICATION',
      clause: '§ 5.2',
      original: 'Receiving Party indemnifies Disclosing Party against all liabilities, claims, expenses, losses and damages.',
      modified: "Receiving Party's liability for breach shall not exceed EUR 10,000 in aggregate.",
      detail: "Indemnification capped at EUR 10,000. Significantly limits the Disclosing Party's recovery.",
      page: 2,
    },
    {
      ruleId: 'DATA_PROTECTION',
      clause: '§ 11',
      original: 'Both parties must comply with applicable Data Protection legislation. Mutual indemnification for data protection breaches.',
      modified: 'Each party shall use reasonable efforts to comply with applicable data protection laws.',
      detail: 'Compliance weakened from strict duty to reasonable efforts. Mutual indemnification removed. GDPR exposure unmitigated.',
      page: 3,
    },
    {
      ruleId: 'ASSIGNMENT',
      clause: '§ 12.6',
      original: 'Agreement may not be assigned without prior express written consent of the other Party.',
      modified: 'Either Party may assign this Agreement to an affiliate or acquirer without consent.',
      detail: 'Assignment permitted to affiliates and acquirers without consent. Could transfer obligations to unknown entities.',
      page: 3,
    },
    {
      ruleId: 'USE_RESTRICTION',
      clause: '§ 3.2',
      original: 'Confidential Information may only be used to evaluate the Opportunity.',
      modified: 'Receiving Party may use Confidential Information for internal business purposes related to the Opportunity or similar opportunities.',
      detail: 'Permitted use expanded beyond the specific Opportunity to similar opportunities.',
      page: 1,
    },
    {
      ruleId: 'NO_LICENCE',
      clause: '§ 8.2',
      original: 'No right or licence to the Confidential Information or IP of the Disclosing Party is granted or implied.',
      modified: 'Clause removed.',
      detail: 'The no-licence clause deleted entirely. An implied licence to use IP could potentially be argued.',
      page: 2,
    },
  ];
}
